### ISSUE TITLE
Add support for Markdown text formatting

### ISSUE THREAD

**Issue by revolter** [revolter/notepadtab.com#1]
It would help to be able to format text like **bold**, <ins>underline</ins>, ~strikethrough~ and _italics_.

**Comment by clickbrain** [comment]
Maakrdown support would be cool. Maybe a viewer button that renders it to markdown in the browser?

**Comment by revolter** [comment]
Something like that. And that button toggling a query param in the URL.

**Comment by revolter** [comment]
Another use case would be to store links, and then being able to simply click to open them.

**Comment by revolter** [comment]
I managed to add some draft implementation for Markdown support:

<img width="764" alt="image" src="https://github.com/revolter/notepadtab.com/assets/5748627/bf328cfd-94db-41f6-a631-dcd55e4892ff">

**Comment by highonweb** [comment]
Hey @revolter 
When is the markdown support going live?
Happy to help if needed.

**Comment by revolter** [comment]
@highonweb, definitely this week.

Would you please help me test it after I create the PR? 🙏🏻

**Comment by highonweb** [comment]
Sure @revolter
